/***
 * 地图瓦片枚举
 */
export const TILE_TYPE_ENUM = {
  WALL_ROW_START: "ROW_WALL_START",
  WALL_ROW_CENTER: "WALL_ROW_CENTER",
  WALL_ROW_END: "ROW_WALL_END",
  WALL_COLUMN_START: "COLUMN_WALL_START",
  WALL_COLUMN_CENTER: "WALL_COLUMN_CENTER",
  WALL_COLUMN_END: "COLUMN_WALL_END",
  CLIFF_ROW_START: 'CLIFF_ROW_START',
  CLIFF_ROW_CENTER: 'CLIFF_ROW_CENTER',
  CLIFF_ROW_END: 'CLIFF_ROW_END',
  FLOOR: "FLOOR",
  DOOR_ROW: "DOOR_ROW",
  DOOR_COLUMN: "DOOR_COLUMN",
}

/***
 * 活动单位枚举
 */
export const ENEMY_TYPE_ENUM = {
  SKELETON_WOODEN: 'SKELETON_WOODEN',
  SKELETON_IRON: 'SKELETON_IRON',
  STAB_ONE: 'STAB_ONE',
  STAB_TWO: 'STAB_TWO',
  STAB_THREE: 'STAB_THREE',
  FRAG_FLOOR: 'FRAG_FLOOR',
}

/***
 * 角色方向枚举
 */
export const DIRECTION_ENUM = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
}

/***
 * 控制按钮枚举
 */
export const CONTROLLER_ENUM = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
  TURNLEFT: 'TURNLEFT',
  TURNRIGHT: 'TURNRIGHT'
}

/***
 * 角色状态枚举
 */
export const PLAYER_STATE = {
  IDLE: 'IDLE',
  ATTACK: 'ATTACK',
  TURNLEFT: 'TURNLEFT',
  TURNRIGHT: 'TURNRIGHT',
}

/***
 * 事件类型枚举
 */
export const EVENT_ENUM = {
	PLAYER_CTRL: 'PLAYER_CTRL',
	NEXT_LEVEL: 'NEXT_LEVEL',
	REVOKE_STEP: 'REVOKE_STEP',
	RESTART_LEVEL: 'RESTART_LEVEL',
	GAME_OVER: 'GAME_OVER',
}
